[deps]
AbstractMCMC = "80f14c24-f653-4e6a-9b94-39d6b0f70001"
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
AdvancedHMC = "0bf59076-c3b1-5ca4-86bd-e02cd72cde3d"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
JuliaBUGS = "ba9fb4c0-828e-4473-b6a1-cd2560fee5bf"
LogDensityProblems = "6fdf6af0-433a-55f7-b3ed-c6c6e0b8df7c"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
MetaGraphsNext = "fa8bd995-216d-47f1-8a91-f3b68fbeb377"
ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"

[sources]
JuliaBUGS = {path = ".."}

[compat]
Documenter = "1.14"
