[deps]
BridgeStan = "c88b6f0a-829e-4b0b-94b7-f06ab5908f5a"
Chairmarks = "0ca39b1e-fe0b-4e98-acfc-b1656634c4de"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
JuliaBUGS = "ba9fb4c0-828e-4473-b6a1-cd2560fee5bf"
LogDensityProblems = "6fdf6af0-433a-55f7-b3ed-c6c6e0b8df7c"
LogDensityProblemsAD = "996a588d-648d-4e1f-a8f0-a84b347e47b1"
MetaGraphsNext = "fa8bd995-216d-47f1-8a91-f3b68fbeb377"
Mooncake = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
StanLogDensityProblems = "a545de4d-8dba-46db-9d34-4e41d3f07807"
